### ISSUE TITLE
Refresh View in Admin error message

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#3]
@sparkji Error! ERROR: could not create unique index "uc_mvdrs_citation_action_variable_analyzed_sample_num_idx" Detail: Key (citation_num, action_num, analyzed_sample_num, variable_num)=(3603, 81691, 701632, 333) is duplicated.

**Comment by sparkji** [comment]
@annikakj I have cleaned the case 'one specimen with multiple stations', but there is another case, need reloading the paper to solve the issue.
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	0.00000864	ccstp/g
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	0.00000864	ccstp/g
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	0.00000864	ccstp/g
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	8.46	ccstp/g
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	8.46	ccstp/g
3582	3582-S1	GL	UNKNOWN	DISSOLVED GLASS VALUES	He	8.46	ccstp/g

**Comment by annikakj** [comment]
@sparkji 3582 has been reloaded now

**Comment by sparkji** [comment]
finally, all duplicate relationship between specimen and stations of 3603 has been cleaned. The issue for 3582 caused by old result data did not been cleaned when reloading.
Now, view has been refreshed, you could check data on [explore](http://ecstage.earthchem.org)
And I have assigned Bai add a function at ECDB-ADMIN to check duplicated relationship between specimen and station.

**Comment by annikakj** [comment]
Ref 3582 checked and confirming is now correct in ECStage.
