### ISSUE TITLE
Admin refresh error message

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemAdmin2#6]
@sparkji  Refreshed, and got this error:

Error! ERROR: could not create unique index "uc_mvdrs_citation_action_variable_analyzed_sample_num_idx" Detail: Key (citation_num, action_num, analyzed_sample_num, variable_num)=(3557, 81739, 702658, 378) is duplicated.

**Comment by bhchen8** [comment]
I will take a look

**Comment by bhchen8** [comment]
Sorry! I don't know what caused this problem.

**Comment by sparkji** [comment]
It caused by one result with multiple vaules
citation_num 3557  'rock' row 28, column 'BC'
4783433 |    4507386 |    38.2002 | 0.0048 |            |       46 | 2018-12-10
 4782052 |    4507386 |         38 |   2002 |            |       46 | 2018-12-10
I have delete the second one, try refresh again, it should work now.

**Comment by annikakj** [comment]
Tested. Confirming it is fixed
